# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: resume-generator-api
#   labels:
#     app: resume-generator-api
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: resume-generator-api
#   template:
#     metadata:
#       labels:
#         app: resume-generator-api
#     spec:
#       containers:
#       - name: resume-generator-api
#         image: registry.digitalocean.com/your-registry/resume-generator-api:latest
#         ports:
#         - containerPort: 8080
#         env:
#         # Google Docs Configuration
#         - name: GoogleDocs__ServiceAccountCredentials
#           valueFrom:
#             secretKeyRef:
#               name: google-credentials
#               key: service-account.json
#         - name: GoogleDocs__UseCredentialsFile
#           value: "false"
#         - name: GoogleDocs__TemplateFolderId
#           valueFrom:
#             secretKeyRef:
#               name: google-credentials
#               key: template-folder-id
#         - name: GoogleDocs__ApplicationName
#           value: "Resume Generator API"
        
#         # OpenAI Configuration (if needed)
#         - name: OpenAI__ApiKey
#           valueFrom:
#             secretKeyRef:
#               name: openai-credentials
#               key: api-key
#               optional: true
#         - name: OpenAI__OrganizationId
#           valueFrom:
#             secretKeyRef:
#               name: openai-credentials
#               key: organization-id
#               optional: true
        
#         # Claude Configuration (if needed)
#         - name: Claude__ApiKey
#           valueFrom:
#             secretKeyRef:
#               name: claude-credentials
#               key: api-key
#               optional: true
        
#         # Health check
#         livenessProbe:
#           httpGet:
#             path: /health
#             port: 8080
#           initialDelaySeconds: 30
#           periodSeconds: 10
#         readinessProbe:
#           httpGet:
#             path: /health
#             port: 8080
#           initialDelaySeconds: 5
#           periodSeconds: 5
        
#         resources:
#           requests:
#             memory: "256Mi"
#             cpu: "250m"
#           limits:
#             memory: "512Mi"
#             cpu: "500m"
            
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: resume-generator-api-service
# spec:
#   selector:
#     app: resume-generator-api
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8080
#   type: ClusterIP

# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: resume-generator-api-ingress
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     cert-manager.io/cluster-issuer: letsencrypt-prod
#     nginx.ingress.kubernetes.io/rate-limit: "100"
# spec:
#   tls:
#   - hosts:
#     - your-domain.com
#     secretName: resume-generator-tls
#   rules:
#   - host: your-domain.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: resume-generator-api-service
#             port:
#               number: 80